### ISSUE TITLE
Self deployment cannot display icons in the browser

### ISSUE THREAD

**Issue by hausen1012** [seadfeng/favicon-downloader#10]
![image](https://github.com/user-attachments/assets/bab57a67-bfb4-417e-b459-4fbfd97984bf)
![image](https://github.com/user-attachments/assets/dd93c272-a834-4aa1-8a0a-475dfb908f80)
![image](https://github.com/user-attachments/assets/bc05e8d4-551a-4c3d-be8f-10d2216aaa07)

**Comment by seadfeng** [comment]
location china?

This should be a network problem.

**Comment by seadfeng** [comment]
> ![image](https://private-user-images.githubusercontent.com/50026605/363863833-bab57a67-bfb4-417e-b459-4fbfd97984bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTY1NjIsIm5iZiI6MTcyNTM1NjI2MiwicGF0aCI6Ii81MDAyNjYwNS8zNjM4NjM4MzMtYmFiNTdhNjctYmZiNC00MTdlLWI0NTktNGZiZmQ5Nzk4NGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA5Mzc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhM2EyODUxNjJjZTJkOThiMGQ3NDY2YjFmNWYyNTZkYTJlMzU3NGUxYmQ1YWNjY2VkZGI5NmRhN2NmZjQ3ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gmshQVYh9tgJ4jII7gZuEvNOLbbkzbmaMpEfzWZ3Hus) ![image](https://private-user-images.githubusercontent.com/50026605/363863889-dd93c272-a834-4aa1-8a0a-475dfb908f80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTY1NjIsIm5iZiI6MTcyNTM1NjI2MiwicGF0aCI6Ii81MDAyNjYwNS8zNjM4NjM4ODktZGQ5M2MyNzItYTgzNC00YWExLThhMGEtNDc1ZGZiOTA4ZjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA5Mzc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExODY0MTgyNDBhZDNkYzQyNjcwOGExNThiYTE0MTI0MmI4ZTkyNzY0ODMzN2VlYTBlM2MxOWVjMWMzMTk5MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AL8LuR3IT4keHHGkaOtRddo_FIRspf27MHQ-drSlCFs) ![image](https://private-user-images.githubusercontent.com/50026605/363865369-bc05e8d4-551a-4c3d-be8f-10d2216aaa07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTY1NjIsIm5iZiI6MTcyNTM1NjI2MiwicGF0aCI6Ii81MDAyNjYwNS8zNjM4NjUzNjktYmMwNWU4ZDQtNTUxYS00YzNkLWJlOGYtMTBkMjIxNmFhYTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA5Mzc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNjIzZDc2ZGNiYjdmMGUxOTFhMzU5ZDAyZWJjZDFiNDAwODg0NGJmMzBiZTgzOTU4NzY1NDc1Mjk0NjI2NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AT46NxjE-nrZiQtfPvCSWHroz4_i-3ZCuPQ0uLArPuM)

location china?

This should be a network problem.

**Comment by hausen1012** [comment]
即使我使用美国服务器，也会有一样的情况。


但我发现，使用ip没有这个问题，而使用域名会有这个问题。


http://142.171.142.114:8800/


![image](https://github.com/user-attachments/assets/de429afe-fefe-4c00-a874-46305784888b)

http://rn2.153224.xyz:8800/

![image](https://github.com/user-attachments/assets/be29f35e-5c34-4233-addb-a583c05efa7e)

**Comment by seadfeng** [comment]
> Even if I use a US server, the same situation will still occur.
> 
> But I found that using IP does not have this problem, while using domain names does.
> 
> http://142.171.142.114:8800/
> 
> ![image](https://private-user-images.githubusercontent.com/50026605/363931266-de429afe-fefe-4c00-a874-46305784888b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTg5MTMsIm5iZiI6MTcyNTM1ODYxMywicGF0aCI6Ii81MDAyNjYwNS8zNjM5MzEyNjYtZGU0MjlhZmUtZmVmZS00YzAwLWE4NzQtNDYzMDU3ODQ4ODhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDEwMTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0OTk2ZmZjMTgwOGRkNzI3OTAwZjQ5YzY1Y2NiZTFkMTAyYTJlNDAwYWEyZDdlN2IzOTNkZWE1YmZmYTEyNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kQEskRxsFEpvgoyG5alH_oWniT09jfWV2nOHJlaFupE)
> 
> http://rn2.153224.xyz:8800/
> 
> ![image](https://private-user-images.githubusercontent.com/50026605/363931382-be29f35e-5c34-4233-addb-a583c05efa7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTg5MTMsIm5iZiI6MTcyNTM1ODYxMywicGF0aCI6Ii81MDAyNjYwNS8zNjM5MzEzODItYmUyOWYzNWUtNWMzNC00MjMzLWFkZGItYTU4M2MwNWVmYTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDEwMTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiODQwOTE3MDNiOTM0NDRkYzU0ODU5ZDZlNmNjZWFhZGVmMTc3ZTI2NzgyNjVmNTQ4MzcxMDgxZjI2ZjcyYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.37gA_8CsMCauSkmamm4vUnTc-Nzwz6I1_bYYlWeAjuA)

Try the new version,  I've updated the code in the image section

**Comment by seadfeng** [comment]
It is recommended to use cloudflare pages for deployment,  If you don't enable ssl, it's easy to have security issues

**Comment by seadfeng** [comment]
> Even if I use a US server, the same situation will still occur.
> 
> But I found that using IP does not have this problem, while using domain names does.
> 
> http://142.171.142.114:8800/
>   

It is recommended to use cloudflare pages for deployment,  If you don't enable ssl, it's easy to have security issues

**Comment by hausen1012** [comment]
I tried the latest image, used a non Chinese Mainland server, and started ssl, but the icon displayed on the interface seems incorrect.
This is my website: https://favicon.153224.xyz/

![image](https://github.com/user-attachments/assets/c12d3493-7568-4135-8f01-593e73c63963)

The program has found the website icon and should not display the letter 'w'.
﻿
The Docker logs are as follows:

![image](https://github.com/user-attachments/assets/655f1f1c-9d4e-4fb0-8dc4-b7f39c24604e)

**Comment by seadfeng** [comment]
> I tried the latest image, used a non Chinese Mainland server, and started ssl, but the icon displayed on the interface seems incorrect. This is my website: https://favicon.153224.xyz/
> 
> ![image](https://private-user-images.githubusercontent.com/50026605/364202260-c12d3493-7568-4135-8f01-593e73c63963.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MjY2ODAsIm5iZiI6MTcyNTQyNjM4MCwicGF0aCI6Ii81MDAyNjYwNS8zNjQyMDIyNjAtYzEyZDM0OTMtNzU2OC00MTM1LThmMDEtNTkzZTczYzYzOTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA1MDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NWE0YzVlZWM1MGYxZjljNWE0OGEwYWQyYWY4Y2EzZGE2OWMyZTI2YzNkYzBmMmZlMjI4NzMyOTVhYzdjMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.shfwlIMQEkYeafK3YjTML6nMECGN0hLNzd5ISY7t5kI)
> 
> The program has found the website icon and should not display the letter 'w'. ﻿ The Docker logs are as follows:
> 
> ![image](https://private-user-images.githubusercontent.com/50026605/364202537-655f1f1c-9d4e-4fb0-8dc4-b7f39c24604e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MjY2ODAsIm5iZiI6MTcyNTQyNjM4MCwicGF0aCI6Ii81MDAyNjYwNS8zNjQyMDI1MzctNjU1ZjFmMWMtOWQ0ZS00ZmIwLThkYzQtYjdmMzljMjQ2MDRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA1MDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwODI5MGZjMWUzMzhlOTE1MzIwYWUwZmI0MGY2MGE0OTI5MTJiNGMyZTU1MTlhY2NjMWFiMmNjMDJkOTAwMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jmN7rVJAGcTuYh4d7JfaLfMZ81bDcUitanfqXZF0dBc)
> 
> https://icons.duckduckgo.com/ip3/www.amjun.com.ico Can display correctly

Login your docker and try:

```bash
curl -I https://icons.duckduckgo.com/ip3/www.amjun.com.ico
```

**Comment by hausen1012** [comment]
![image](https://github.com/user-attachments/assets/582c553d-9284-460a-8cdf-d4bdf61a8071)

**Comment by seadfeng** [comment]
> ![image](https://private-user-images.githubusercontent.com/50026605/364232862-582c553d-9284-460a-8cdf-d4bdf61a8071.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzEwNTMsIm5iZiI6MTcyNTQzMDc1MywicGF0aCI6Ii81MDAyNjYwNS8zNjQyMzI4NjItNTgyYzU1M2QtOTI4NC00NjBhLThjZGYtZDRiZGY2MWE4MDcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA2MTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzN2I4MTFlMmVmNzFhZjc4MzJiOGUyNDU0YjEzOTYzYzJiZGYyNDNlM2M0N2YzYjU2ZWMzNDliNzZmNmRiZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DBk6-6t2_3I0HksgxfMUlxYdB_s3tejNLWh51fG8jfo)


1. create test.js

```js
// test.js
const response = fetch("https://icons.duckduckgo.com/ip3/www.amjun.com.ico", { 
  redirect: 'follow'
}).then((response)=>{ 
  console.log("response.status", response.status) 
})
```
3. run test 

```sh
node test.js
```

**Comment by hausen1012** [comment]
![image](https://github.com/user-attachments/assets/410d0c3a-8ffd-4393-a289-90b8d9567322)

It looks normal

**Comment by seadfeng** [comment]
> ![image](https://private-user-images.githubusercontent.com/50026605/364253581-410d0c3a-8ffd-4393-a289-90b8d9567322.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzU1NDMsIm5iZiI6MTcyNTQzNTI0MywicGF0aCI6Ii81MDAyNjYwNS8zNjQyNTM1ODEtNDEwZDBjM2EtOGZmZC00MzkzLWEyODktOTBiOGQ5NTY3MzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA3MzQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNTNlZWE4NjQxMzBlMzFhMzkyZmQ3N2FkMmFjZWZlNTA4YzcyYTcwZGYzYzNhZDg3N2FjZTRiMjE5NDgwODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YRFmr5d_FZji5PkoJPMw1ibZgqA3kQrfIgQ3esrEOes)
> 
> It looks normal

The reason was found, the new version is released normally, the release is complete, please update your docker version

https://github.com/seadfeng/favicon-downloader/actions/runs/10697181077

**Comment by hausen1012** [comment]
It looks normal, but I'm not sure why its self built version is so blurry, while your pages website is clear. 

![image](https://github.com/user-attachments/assets/e7514dda-b75a-443f-a85d-ad09e312d31d)
![image](https://github.com/user-attachments/assets/4bc5cf6e-de73-4cb9-8f65-6c097e0c1165)

**Comment by seadfeng** [comment]
> It looks normal, but I'm not sure why its self built version is so blurry, while your pages website is clear.
> 
> ![image](https://private-user-images.githubusercontent.com/50026605/364276583-e7514dda-b75a-443f-a85d-ad09e312d31d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzkxMzUsIm5iZiI6MTcyNTQzODgzNSwicGF0aCI6Ii81MDAyNjYwNS8zNjQyNzY1ODMtZTc1MTRkZGEtYjc1YS00NDNmLWE4NWQtYWQwOWUzMTJkMzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA4MzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ZDA5OWNkZTUyODkzNGY5YmUwOGE4OGZiZTVhNTZiOTFhZDZlZDMzMWNkZDYxODE3NjMxNjVmOTUyNWI1MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MFGLi0hOKUjQSMN2WOYRkacFh4cpYwFpmy09jRfcDiY) ![image](https://private-user-images.githubusercontent.com/50026605/364276657-4bc5cf6e-de73-4cb9-8f65-6c097e0c1165.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzkxMzUsIm5iZiI6MTcyNTQzODgzNSwicGF0aCI6Ii81MDAyNjYwNS8zNjQyNzY2NTctNGJjNWNmNmUtZGU3My00Y2I5LThmNjUtNmMwOTdlMGMxMTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA4MzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNGE3MWVkMDY4ZTMyMDE5ODgzMjNmZGVjZDFhZDJhZWFlMGU1OTAxOGY2ODNlZmNjYWQ4Zjg2NWRjYzU1ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IPEkbAQVocfkWxt3tlH1Ekk1VPAZAFo1kVhtEijWJ1E)

caused by the wrong type of headers, cloudflare automatically fixed the headers; just modified the missing paragraph, the new version is in the process of being released

**Comment by hausen1012** [comment]
It's normal, thank you very much, but I still have a few ideas. I think I may need to open another issue
