### ISSUE TITLE
features request

### ISSUE THREAD

**Issue by hausen1012** [seadfeng/favicon-downloader#11]
Thank you very much for developing such a user-friendly program

I use the favicon downloader as a way to obtain navigation website icons, but I have three questions when using it.

1. Due to my navigation website having a large collection of websites, icon display is very slow when there are a large number of requests

I personally think that this can be done using caching. When a favicon downloader requests an icon, it will cache the icon locally, wait for the next request, and return directly. Of course, this cache also has a time limit, such as setting how many days it will be automatically cleared.

2. I hope to add a request method that carries suffixes

For example https://favicon.153224.xyz/favicon/www.amjun.com When this request https://favicon.153224.xyz/favicon/www.amjun.com.png It can also respond correctly, so that when the first request is initiated and the browser requests again later, there will be cache, so there is no need to request the server. Of course, this can actually be solved through nginx configuration.

3. When my website is an internal IP address, I cannot obtain the icon

Even though I knew it was normal to not be able to obtain it, at that time I thought it was possible to return a default icon?

![image](https://github.com/user-attachments/assets/cf73af76-9b64-452c-b7a0-96a7bb1facf6)

I'm not sure if some of the above issues can be resolved. Looking forward to your reply

**Comment by seadfeng** [comment]
> Thank you very much for developing such a user-friendly program
> 
> I use the favicon downloader as a way to obtain navigation website icons, but I have three questions when using it.
> 
> 1. Due to my navigation website having a large collection of websites, icon display is very slow when there are a large number of requests
> 
> I personally think that this can be done using caching. When a favicon downloader requests an icon, it will cache the icon locally, wait for the next request, and return directly. Of course, this cache also has a time limit, such as setting how many days it will be automatically cleared.
> 
> 2. I hope to add a request method that carries suffixes
> 
> For example https://favicon.153224.xyz/favicon/www.amjun.com When this request https://favicon.153224.xyz/favicon/www.amjun.com.png It can also respond correctly, so that when the first request is initiated and the browser requests again later, there will be cache, so there is no need to request the server. Of course, this can actually be solved through nginx configuration.
> 
> 3. When my website is an internal IP address, I cannot obtain the icon
> 
> Even though I knew it was normal to not be able to obtain it, at that time I thought it was possible to return a default icon?
> 
> ![image](https://private-user-images.githubusercontent.com/50026605/364303765-cf73af76-9b64-452c-b7a0-96a7bb1facf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDEzMjYsIm5iZiI6MTcyNTQ0MTAyNiwicGF0aCI6Ii81MDAyNjYwNS8zNjQzMDM3NjUtY2Y3M2FmNzYtOWI2NC00NTJjLWI3YTAtOTZhN2JiMWZhY2Y2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA5MTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NTBlZTBhMGIzMjhkNmQ3ODRjMWE4NTE5ZTFlMmU3ZDY2NDc0ZTVjZWIyNmNkNGUzNDUwODk5M2E2YTM3ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jUaMA4Uo4e7ycYkkOdE_0M5afFqp6LYU-r17ga-kvpc)
> 
> I'm not sure if some of the above issues can be resolved. Looking forward to your reply

Images are recommended to use lazy loading, and images are loaded to ensure speed, it is recommended to use the
https://github.com/seadfeng/favicons-proxy repository, directly copy the code to workers deployment can be, this version does not use web scraper, just proxy, so the speed is very fast.

Want to cache images to the server, please solve the problem by yourself, this tool mainly runs on cloudflare pages, edge function is not support image storage, need additional S3 storage to support ;

However, running in docker nodejs does not have this limitation, you can expand according to demand

**Comment by hausen1012** [comment]
I understand, thank you

**Comment by hausen1012** [comment]
Even if it cannot be stored, I still think there are two requests to see if they can be added.
1. Requests can be made by adding a suffix.
Like https://api.iowen.cn/favicon/www.amjun.com.png This request, check if it has a png suffix, remove the suffix before requesting the website icon
When the requested domain name is invalid, return the default image instead of 400
For example, when there is an internal network address in the navigation, there will be no request failure

**Comment by seadfeng** [comment]
> Even if it cannot be stored, I still think there are two requests to see if they can be added.
> 
> 1. Requests can be made by adding a suffix.
>    Like https://api.iowen.cn/favicon/www.amjun.com.png This request, check if it has a png suffix, remove the suffix before requesting the website icon
> 2. When the requested domain name is invalid, return the default image instead of 400
>    For example, when there is an internal network address in the navigation, there will be no request failure

1.source image may be gif, jpg or others, So using png as a suffix is not appropriate .

2. return changed: https://39e48098.favicon-3j1.pages.dev/favicon/11.11

**Comment by hausen1012** [comment]
ok，Can special treatment be given to these suffixes?

**Comment by seadfeng** [comment]
> ok，Can special treatment be given to these suffixes?

https://github.com/seadfeng/favicon-downloader/blob/rewrites/next.config.mjs

Try changing it like this.
 
```js
{
        source: '/favicon/:domain((?:[a-z0-9-]+\\.)+[a-z0-9]{1,}).png',
        destination: '/favicon/:domain',
}
```

**Comment by hausen1012** [comment]
> > ok，Can special treatment be given to these suffixes?
> 
> https://github.com/seadfeng/favicon-downloader/blob/rewrites/next.config.mjs
> 
> Try changing it like this.
> 
> ```js
> {
>         source: '/favicon/:domain((?:[a-z0-9-]+\\.)+[a-z0-9]{1,}).png',
>         destination: '/favicon/:domain',
> }
> ```

thanks
