### ISSUE TITLE
Get icon bug

### ISSUE THREAD

**Issue by hausen1012** [seadfeng/favicon-downloader#12]
不能获取某些图标，并且也不会生成字母图标，而是返回 `Failed to fetch the icon`，这种情况应该返回字母图标才对？

例如：[https://favicon.153224.xyz/favicon/hot.amjun.com.png](https://favicon.153224.xyz/favicon/hot.amjun.com.png)

![image](https://github.com/user-attachments/assets/208b8ac1-25c1-4e29-99bf-ce6f72af06fb)

**Comment by hausen1012** [comment]
![image](https://github.com/user-attachments/assets/54d3fa81-e9fb-47ec-a8b6-d34f91ad9083)

The path here has obvious errors, I'm not sure if it's related

**Comment by seadfeng** [comment]
> 不能获取某些图标，并且也不会生成字母图标，而是返回 `Failed to fetch the icon`，这种情况应该返回字母图标才对？
> 
> 例如：https://favicon.153224.xyz/favicon/hot.amjun.com.png
> 

relative path issues:  

```html
<link rel="icon" href="ico/favicon.png" />
```

https://f7adc314.favicon-3j1.pages.dev/favicon/hot.amjun.com

**Comment by seadfeng** [comment]
> ![image](https://private-user-images.githubusercontent.com/50026605/364693879-54d3fa81-e9fb-47ec-a8b6-d34f91ad9083.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MjYxMzksIm5iZiI6MTcyNTUyNTgzOSwicGF0aCI6Ii81MDAyNjYwNS8zNjQ2OTM4NzktNTRkM2ZhODEtZTlmYi00N2VjLWE4YjYtZDM0ZjkxYWQ5MDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDA4NDM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MzYzMTczY2UyNzQwZTQ3ZWU2ZTgyNGVmOTEwZDQ4MmEyOGVkN2Q2OGVhNTA2ZDM3MmU5NDUyN2NhNzIzZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ltY1f9HNEjP9vMVi1IYpIdY34J_hwFmibfBxbCN8kZo)
> 
> The path here has obvious errors, I'm not sure if it's related

Img src is OK, use the new version

![image](https://github.com/user-attachments/assets/79c5da80-20f8-4890-801e-58745352c4bf)

**Comment by seadfeng** [comment]
> The path here has obvious errors, I'm not sure if it's related

Regular Packaging and Deployment

https://github.com/seadfeng/favicon-downloader/actions/runs/10716944191

**Comment by hausen1012** [comment]
Okay, thank you. I just realized that I forgot to translate it. Sorry
