### ISSUE TITLE
Larger Size does not work in some websites.

### ISSUE THREAD

**Issue by shenweiyan** [seadfeng/favicon-downloader#15]
For example, the website `mail.qq.com` seems to only be able to obtain the default 16x16 icon size, and other sizes of icons fail to be obtained.

![20241211 154748](https://github.com/user-attachments/assets/73929171-5810-462a-b7f1-2ed312c24ded)

**Comment by seadfeng** [comment]
> For example, the website `mail.qq.com` seems to only be able to obtain the default 16x16 icon size, and other sizes of icons fail to be obtained.
> 
> ![20241211 154748](https://private-user-images.githubusercontent.com/26101369/394627710-73929171-5810-462a-b7f1-2ed312c24ded.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MDUwODgsIm5iZiI6MTczMzkwNDc4OCwicGF0aCI6Ii8yNjEwMTM2OS8zOTQ2Mjc3MTAtNzM5MjkxNzEtNTgxMC00NjJhLWI3ZjEtMmVkMzEyYzI0ZGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDA4MTMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZWM5Y2RiOTFmYmM2OGJhNjdhYTA4ZDFhNzQyMjExNzkyYjBhNGQ4YTk5ZWYzNGJiYzljMzZmZWNlZTMzYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QDFNV7fFknvqkFHkLMSpIIQh-8sP3DwqJ7s3dU3W_DA)

不是所有站点都有大图

**Comment by shenweiyan** [comment]
F12 看了一下，其他尺寸的 favicon 也是有的。

![20241211 164612](https://github.com/user-attachments/assets/86198d3b-1f8e-4ccb-b7fd-6f97cd8f5c98)

也看了一下 <https://favicon.im/> 的这个站点，发现 `https://favicon.im/mail.qq.com?larger=true` 的确有 Larger Size >.<

![20241211 165147](https://github.com/user-attachments/assets/1df81adb-aed8-4f41-a6fa-52aa3109484d)

**Comment by seadfeng** [comment]
看了下源码，HTML不符合标准, src 没有引号负值，正则匹配不到。

![image](https://github.com/user-attachments/assets/12afa5bf-710e-490a-bf83-f37815e74f96)

**Comment by shenweiyan** [comment]
> 看了下源码，HTML不符合标准, href 没有引号 ，正则匹配不到。

请问一下，正则匹配是在 `src/lib/server.ts` 里面进行调整吗？尝试了一下，但发现不起作用。

另外，"Larger Size" 对一些网站，好像会跟默认的尺寸混淆，如 `baidu.com`。
![20241212 102324](https://github.com/user-attachments/assets/c00ac8b1-233b-4ac7-b834-84e5059457f7)

**Comment by seadfeng** [comment]
已改进，预览：
https://d0bc7bd9.favicon-3j1.pages.dev/

**Comment by shenweiyan** [comment]
感谢更新，通过更新匹配规则，的确能获取到非标准 HTML 的 favicon！

Larger Size 的体验总体还是没有 <https://favicon.im/> 好，再次感谢。
