### ISSUE TITLE
sizes dont show

### ISSUE THREAD

**Issue by iamLazyCode** [seadfeng/favicon-downloader#2]
i have to say this is a great tool , i am glad to find this project
but i have few doubts why there is always some kind of loading going on and why always says `unknown size`

![image](https://github.com/user-attachments/assets/3e069224-a601-492a-8640-e20e9ba6e87c)

**Comment by seadfeng** [comment]
> i have to say this is a great tool , i am glad to find this project but i have few doubts why there is always some kind of loading going on and why always says `unknown size`
> 
> ![image](https://private-user-images.githubusercontent.com/13099434/359804827-3e069224-a601-492a-8640-e20e9ba6e87c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzQ0NjQsIm5iZiI6MTcyNDIzNDE2NCwicGF0aCI6Ii8xMzA5OTQzNC8zNTk4MDQ4MjctM2UwNjkyMjQtYTYwMS00OTJhLTg2NDAtZTIwZTliYTZlODdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA5NTYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiM2VhY2NmZWUwMmJhNDA0NmIzYzE3NjQxMjViNzEwMGIwYjdlMDI5ZmJjNzhiNDFiYmY5NmE1M2YwMDdlOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3F-UUXOUu6gRsZ5CgUxWsMBfQNFAg8dxXc9eUIQlg6c)

Size issue fixed

![image](https://github.com/user-attachments/assets/6c5efe28-8547-45c1-9dfe-0d3edd5549b4)

**Comment by iamLazyCode** [comment]
> > i have to say this is a great tool , i am glad to find this project but i have few doubts why there is always some kind of loading going on and why always says `unknown size`
> > ![image](https://private-user-images.githubusercontent.com/13099434/359804827-3e069224-a601-492a-8640-e20e9ba6e87c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzQ0NjQsIm5iZiI6MTcyNDIzNDE2NCwicGF0aCI6Ii8xMzA5OTQzNC8zNTk4MDQ4MjctM2UwNjkyMjQtYTYwMS00OTJhLTg2NDAtZTIwZTliYTZlODdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA5NTYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiM2VhY2NmZWUwMmJhNDA0NmIzYzE3NjQxMjViNzEwMGIwYjdlMDI5ZmJjNzhiNDFiYmY5NmE1M2YwMDdlOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3F-UUXOUu6gRsZ5CgUxWsMBfQNFAg8dxXc9eUIQlg6c)
> 
> Size issue fixed
> 
> ![image](https://private-user-images.githubusercontent.com/9997707/359848658-6c5efe28-8547-45c1-9dfe-0d3edd5549b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzc0MzUsIm5iZiI6MTcyNDIzNzEzNSwicGF0aCI6Ii85OTk3NzA3LzM1OTg0ODY1OC02YzVlZmUyOC04NTQ3LTQ1YzEtOWRmZS0wZDNlZGQ1NTQ5YjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjFUMTA0NTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTM4MWIyYzg2OGU1N2NhN2Q2MWE4NGQ1ZjRlYzA4MDhkNWZlZGY5ZTM0MDA4MDRiNTQ5ZWZiOTMwNDliZjFkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ah-vYX9uQaqbnSBmRd4Fw_l_NGGsHZeDJYeiBL7ciP4)

thankyou so much for quick response and fix :)
