### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by mariushosting** [seadfeng/favicon-downloader#6]
Can you please add a Docker image for this?

**Comment by seadfeng** [comment]
> Can you please add a Docker image for this?


Try this docker build

```sh
sh ./bin/docker.sh
```

https://github.com/seadfeng/favicon-downloader/tree/main/.docker

**Comment by mariushosting** [comment]
Can you build the image for US?

**Comment by seadfeng** [comment]
> Can you build the image for US?

Docker online Image

```sh
docker pull seadfeng/font-generator
docker run -p 3000:3000 seadfeng/font-generator
```

**Comment by seadfeng** [comment]
> Can you build the image for US?

Online Image
```sh
docker pull seadfeng/favicon-downloader
docker run -p 3000:3000 seadfeng/favicon-downloader
```

**Comment by mariushosting** [comment]
> > Can you build the image for US?
> 
> Online Image
> 
> ```shell
> docker pull seadfeng/favicon-downloader
> docker run -p 3000:3000 seadfeng/favicon-downloader
> ```
@seadfeng 
Image is working. But there is some issues in the logs and the rendered image is not visible.
![issues](https://github.com/user-attachments/assets/7fed5af0-b14a-4443-abf8-d605f3d4c093)

also the app put https:// at the beginning even in localhost. If we want to use it in localhost the link should be with http instead of https
<img alt="Favicon" src="**https**://192.168.1.18:3000/favicon/mariushosting.com" />

Also if I use reverse proxy the rendered image is the default "Favicon Downloader icon" instead of the favicon that we want to download
![your favicon](https://github.com/user-attachments/assets/84c12713-ceb5-43ce-b34e-cdf43ae9ec8a)

**Comment by seadfeng** [comment]
F

> > > Can you build the image for US?
> > 
> > 
> > Online Image
> > ```shell
> > docker pull seadfeng/favicon-downloader
> > docker run -p 3000:3000 seadfeng/favicon-downloader
> > ```
> 
> @seadfeng Image is working. But there is some issues in the logs and the rendered image is not visible. ![issues](https://private-user-images.githubusercontent.com/37554361/361134525-7fed5af0-b14a-4443-abf8-d605f3d4c093.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MDYxMDQsIm5iZiI6MTcyNDUwNTgwNCwicGF0aCI6Ii8zNzU1NDM2MS8zNjExMzQ1MjUtN2ZlZDVhZjAtYjE0YS00NDQzLWFiZjgtZDYwNWYzZDRjMDkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDEzMjMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZGI1NzEyMDlhZDQ4ZWE2NzEyM2QxMmM5NGFkZDkwYzk4NjFkNzI3MDBiOGQzNzQyY2RmZjc1MzRmOTBiOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QaratexRwlL-8ZiX6G6IE6b1uCn_LIJ4ki7L0k3noKs)
> 
> also the app put https:// at the beginning even in localhost. If we want to use it in localhost the link should be with http instead of https img alt="Favicon" src="**https**://192.168.1.18:3000/favicon/mariushosting.com" /
> 
> Also if I use reverse proxy the rendered image is the default "Favicon Downloader icon" instead of the favicon that we want to download ![your favicon](https://private-user-images.githubusercontent.com/37554361/361134691-84c12713-ceb5-43ce-b34e-cdf43ae9ec8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MDYxMDQsIm5iZiI6MTcyNDUwNTgwNCwicGF0aCI6Ii8zNzU1NDM2MS8zNjExMzQ2OTEtODRjMTI3MTMtY2ViNS00M2NlLWIzNGUtY2RmNDNhZTllYzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDEzMjMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYzExMmYxMWJlOWJmZDQ3NGJjMWVjZDRhNDk3YmZlZDNhZjFkMGEzNzI2OTg1Mjc0MzMxYjY3NjdjZDFjZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w27L4TS5Ciq_euKtZ__2K1O3HAJINeWL1Eta0l73LuQ)

Thanks for the feedback, the new version fixes the `protocol` problem.

Pls, pull the new image 

```sh
docker pull seadfeng/favicon-downloader:latest
```

**Comment by mariushosting** [comment]
> F
> 
> > > > Can you build the image for US?
> > > 
> > > 
> > > Online Image
> > > ```shell
> > > docker pull seadfeng/favicon-downloader
> > > docker run -p 3000:3000 seadfeng/favicon-downloader
> > > ```
> > 
> > 
> > @seadfeng Image is working. But there is some issues in the logs and the rendered image is not visible. ![issues](https://private-user-images.githubusercontent.com/37554361/361134525-7fed5af0-b14a-4443-abf8-d605f3d4c093.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MDYxMDQsIm5iZiI6MTcyNDUwNTgwNCwicGF0aCI6Ii8zNzU1NDM2MS8zNjExMzQ1MjUtN2ZlZDVhZjAtYjE0YS00NDQzLWFiZjgtZDYwNWYzZDRjMDkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDEzMjMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZGI1NzEyMDlhZDQ4ZWE2NzEyM2QxMmM5NGFkZDkwYzk4NjFkNzI3MDBiOGQzNzQyY2RmZjc1MzRmOTBiOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QaratexRwlL-8ZiX6G6IE6b1uCn_LIJ4ki7L0k3noKs)
> > also the app put https:// at the beginning even in localhost. If we want to use it in localhost the link should be with http instead of https img alt="Favicon" src="**https**://192.168.1.18:3000/favicon/mariushosting.com" /
> > Also if I use reverse proxy the rendered image is the default "Favicon Downloader icon" instead of the favicon that we want to download ![your favicon](https://private-user-images.githubusercontent.com/37554361/361134691-84c12713-ceb5-43ce-b34e-cdf43ae9ec8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MDYxMDQsIm5iZiI6MTcyNDUwNTgwNCwicGF0aCI6Ii8zNzU1NDM2MS8zNjExMzQ2OTEtODRjMTI3MTMtY2ViNS00M2NlLWIzNGUtY2RmNDNhZTllYzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDEzMjMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYzExMmYxMWJlOWJmZDQ3NGJjMWVjZDRhNDk3YmZlZDNhZjFkMGEzNzI2OTg1Mjc0MzMxYjY3NjdjZDFjZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w27L4TS5Ciq_euKtZ__2K1O3HAJINeWL1Eta0l73LuQ)
> 
> Thanks for the feedback, the new version fixes the `protocol` problem.
> 
> Pls, pull the new image
> 
> ```shell
> docker pull seadfeng/favicon-downloader:latest
> ```

Works like a charm!
