### ISSUE TITLE
How do I remove the /favicon from the URL?

### ISSUE THREAD

**Issue by dishao123** [seadfeng/favicon-downloader#7]
Hello, I want to change the URL to `example.com/proxysites.ai` and `example.com/api/proxysites.ai`. What do I need to do?

**Comment by seadfeng** [comment]
> Hello, I want to change the URL to `example.com/proxysites.ai` and `example.com/api/proxysites.ai`. What do I need to do?

**example.com/api/proxysites.ai**
Change Path: src/app/api/favicon/[domain] => src/app/api/[domain]

**example.com/proxysites.ai**

```ts
// next.config.mjs
const nextConfig = {
  output: 'standalone',
  eslint: {
    dirs: ["src"],
  },
  //  change the URL to example.com/proxysites.ai
  async rewrites() {
    return [
      {
        source: '/:domain([a-z0-9-]+\\.[a-z]{2,})',
        destination: '/api/favicon/:domain',
      }
    ]
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**',
      },
      {
        protocol: 'http',
        hostname: '**',
      },
    ],
  },
};
```

**Comment by dishao123** [comment]
> > Hello, I want to change the URL to `example.com/proxysites.ai` and `example.com/api/proxysites.ai`. What do I need to do?
> 
> **example.com/api/proxysites.ai** Change Path: src/app/api/favicon/[domain] => src/app/api/[domain]
> 
> **example.com/proxysites.ai**
> 
> ```ts
> // next.config.mjs
> const nextConfig = {
>   output: 'standalone',
>   eslint: {
>     dirs: ["src"],
>   },
>   //  change the URL to example.com/proxysites.ai
>   async rewrites() {
>     return [
>       {
>         source: '/:domain([a-z0-9-]+\\.[a-z]{2,})',
>         destination: '/api/favicon/:domain',
>       }
>     ]
>   },
>   images: {
>     remotePatterns: [
>       {
>         protocol: 'https',
>         hostname: '**',
>       },
>       {
>         protocol: 'http',
>         hostname: '**',
>       },
>     ],
>   },
> };
> ```

What I want to achieve is
example.com/favicon/proxysites.ai => example.com/proxysites.ai

example.com/api/favicon/proxysites.ai => example.com/api/proxysites.ai

Remove the /favicon parameter in the url route

What needs to be modified?

**Comment by seadfeng** [comment]
> > > Hello, I want to change the URL to `example.com/proxysites.ai` and `example.com/api/proxysites.ai`. What do I need to do?
> > 
> > 
> > **example.com/api/proxysites.ai** Change Path: src/app/api/favicon/[domain] => src/app/api/[domain]
> > **example.com/proxysites.ai**
> > ```ts
> > // next.config.mjs
> > const nextConfig = {
> >   output: 'standalone',
> >   eslint: {
> >     dirs: ["src"],
> >   },
> >   //  change the URL to example.com/proxysites.ai
> >   async rewrites() {
> >     return [
> >       {
> >         source: '/:domain([a-z0-9-]+\\.[a-z]{2,})',
> >         destination: '/api/favicon/:domain',
> >       }
> >     ]
> >   },
> >   images: {
> >     remotePatterns: [
> >       {
> >         protocol: 'https',
> >         hostname: '**',
> >       },
> >       {
> >         protocol: 'http',
> >         hostname: '**',
> >       },
> >     ],
> >   },
> > };
> > ```
> 
> What I want to achieve is example.com/favicon/proxysites.ai => example.com/proxysites.ai
> 
> example.com/api/favicon/proxysites.ai => example.com/api/proxysites.ai
> 
> Remove the /favicon parameter in the url route
> 
> What needs to be modified?

Sorry, use this method, that previous rule was misspelled,

you can pull this branch: 
https://github.com/seadfeng/favicon-downloader/tree/rewrites

A rewrite of the router in this version will do the trick:
 [next.config.mjs](https://github.com/seadfeng/favicon-downloader/blob/rewrites/next.config.mjs)

**Comment by dishao123** [comment]
> > > > Hello, I want to change the URL to `example.com/proxysites.ai` and `example.com/api/proxysites.ai`. What do I need to do?
> > > 
> > > 
> > > **example.com/api/proxysites.ai** Change Path: src/app/api/favicon/[domain] => src/app/api/[domain]
> > > **example.com/proxysites.ai**
> > > ```ts
> > > // next.config.mjs
> > > const nextConfig = {
> > >   output: 'standalone',
> > >   eslint: {
> > >     dirs: ["src"],
> > >   },
> > >   //  change the URL to example.com/proxysites.ai
> > >   async rewrites() {
> > >     return [
> > >       {
> > >         source: '/:domain([a-z0-9-]+\\.[a-z]{2,})',
> > >         destination: '/api/favicon/:domain',
> > >       }
> > >     ]
> > >   },
> > >   images: {
> > >     remotePatterns: [
> > >       {
> > >         protocol: 'https',
> > >         hostname: '**',
> > >       },
> > >       {
> > >         protocol: 'http',
> > >         hostname: '**',
> > >       },
> > >     ],
> > >   },
> > > };
> > > ```
> > 
> > 
> > What I want to achieve is example.com/favicon/proxysites.ai => example.com/proxysites.ai
> > example.com/api/favicon/proxysites.ai => example.com/api/proxysites.ai
> > Remove the /favicon parameter in the url route
> > What needs to be modified?
> 
> Sorry, use this method, that previous rule was misspelled,
> 
> you can pull this branch: https://github.com/seadfeng/favicon-downloader/tree/rewrites
> 
> A rewrite of the router in this version will do the trick: [next.config.mjs](https://github.com/seadfeng/favicon-downloader/blob/rewrites/next.config.mjs)

Thanks

**Comment by dishao123** [comment]
@seadfeng What should I do if I need to add a new Favicon API?

**Comment by seadfeng** [comment]
> @seadfeng What should I do if I need to add a new Favicon API?

You will need to learn `nextjs`
