### ISSUE TITLE
Unable to obtain icon

### ISSUE THREAD

**Issue by hausen1012** [seadfeng/favicon-downloader#9]
url: https://www.faviconextractor.com/favicon/drop.amjun.com

![image](https://github.com/user-attachments/assets/71941537-0586-4614-b44b-ba463c1565a2)

**Comment by seadfeng** [comment]
> url: https://www.faviconextractor.com/favicon/drop.amjun.com
> 
> ![image](https://private-user-images.githubusercontent.com/50026605/363860071-71941537-0586-4614-b44b-ba463c1565a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTQzODMsIm5iZiI6MTcyNTM1NDA4MywicGF0aCI6Ii81MDAyNjYwNS8zNjM4NjAwNzEtNzE5NDE1MzctMDU4Ni00NjE0LWI0NGItYmE0NjNjMTU2NWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA5MDEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNWE0MDAyODYwN2IxMzE5ZGRlZGRkNGE5OWI4ODc2MGZjNTJmZmFkM2NiODU5OGI3OWU4Mzk2ZmM2Y2Q3OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jxz3wL93e6Ygxpx7oIb_ySrS3SMYuCHvhvNMiq3SDpw)

This has been fixed in the new version.

Preview: https://b662ff3c.favicon-3j1.pages.dev/favicon/drop.amjun.com

**Comment by hausen1012** [comment]
ok，thanks
